Add utils: check bash version & internet connection

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,1 +1,34 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+# shellcheck disable=SC1091
+
+# ============================================
+# ERROR: Let the user know if the script fails
+# ============================================
+# @todo: Add trap
+
+# ---
+
+# =================================
+# LOAD UTILITIES: Warn if not found
+# =================================
+
+if [ -e utils ] && . utils; then 
+    check_bash_version
+    check_internet_connection
+    
+else
+    printf "\n ⚠️  ./utils file not found.\n"
+    # exit 1
+fi
+
+
+# @todo:
+# - Ask for sudo password
+# - SSH key setup
+# - Install dependencies: Xcode, Homebrew, NVM(?)
+# - Install brews (the  run `brew update`) and casks
+# - Install Mac App Store applications
+# - Run Homebrew clean-up tasks
+# - Install npm global packages
+# - Any others...?
diff --git a/utils b/utils
--- a/utils
+++ b/utils
@@ -1,1 +1,23 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+minBashVersion=3
+
+# =============
+# SYSTEM CHECKS
+# =============
+
+check_bash_version() {
+    if ((BASH_VERSINFO[0] < "$minBashVersion"))
+    then
+        printf "You need at least bash %s.0 or higher to run this script.\n" $minBashVersion
+        # exit 1
+    fi
+}
+
+check_internet_connection() {
+    if ping -q -c1 google.com &> /dev/null; then
+        printf "Internet connection detected.\n"
+    else
+        printf "Internet connection not found. Please check and try again.\n"
+    fi
+}
